[package]
name = "api_derive"
version = "0.3.1"
authors = ["Andras Mocsary <nobody@reedwolf.com>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1.0.3"
proc-macro2 = "1.0.10"

[dependencies.syn]
version = "1.0.17"
features = ["full"]
